# Generated by Django 4.2 on 2025-04-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"verbose_name": "Borrowing", "verbose_name_plural": "Borrowings"},
        ),
    ]
