# Generated by Django 4.2 on 2025-04-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0003_alter_borrowing_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
