# Generated by Django 5.2 on 2025-04-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowing", "0005_alter_borrowing_borrow_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrow_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
