version: '3'

services:
  backend:
    build: ./
    container_name: libra_container
    working_dir: /libra
    ports:
      - "8010:8000"
    command:
      - ./commands/start_django_server.sh
    volumes:
      - ./src:/libra/src
      - ./commands:/libra/commands
    env_file:
      - .env


  redis:
    image: redis
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - backend

  celery:
    build: ./
    container_name: celery-container
    command:
      - ./commands/start_celery.sh
    restart: on-failure
    volumes:
      - ./src:/libra
      - ./commands:/libra/commands
    env_file:
      - .env
    depends_on:
      - redis
      - backend

  celerybeat:
    build: ./
    container_name: celerybeat-container
    command:
      - ./commands/start_celerybeat.sh
    restart: on-failure
    volumes:
      - ./src:/libra
      - ./commands:/libra/commands
    env_file:
      - .env
    depends_on:
      - redis
      - backend


  flower:
    build: ./
    container_name: flower_container
    volumes:
      - ./src:/libra
    command: celery -A config flower --broker=redis://redis
    ports:
      - "5556:5555"
    depends_on:
      - backend
      - celery
    env_file:
      - .env
